# shellcheck shell=bash

if patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'terminal'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'terminal'}
# shellcheck disable=SC2034
TMUX_POWERLINE_SEG_AIR_COLOR=$(air_color)

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_THIN}

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_CURRENT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_CURRENT=(
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
		" #I#F "
		" #W "
	)
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_STYLE" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_STYLE=(
	)
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_FORMAT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
		"  #I#{?window_flags,#F, } "
		" #W "
	)
fi

# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_LEFT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"tmux_session_info terminal terminal ${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR} no_sep_bg_color no_sep_fg_color no_spacing_disable separator_disable"
	)
fi

# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		"vcs_others terminal aquamarine ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}"
		"vcs_modified terminal aquamarine ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}"
		"vcs_staged terminal aquamarine ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}"
		"vcs_compare terminal aquamarine ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}"
		"vcs_branch terminal aquamarine ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}"
		"pwd terminal aqua ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}"
		"hostname terminal magenta ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}"
		"wan_ip terminal blue ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}"
		"lan_ip terminal blue ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}"
		"time terminal orange ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}"
		"utc_time terminal orange ${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR}"
	)
fi
