disks = ["/"]
disk_space_percentage = true
interface = "en0"
long_uptime = true
memory_percentage = true

show = [
    "Host",
    "Machine",
    "Kernel",
    "OperatingSystem",
    "Shell",
    "Terminal",
    "Resolution",
    "Processor",
    "ProcessorLoad",
    "GPU",
    "Memory",
    "DiskSpace",
    "LocalIP",
    "Uptime",
    "Battery",
]

